def get_name():
    return "vaayu kapoor"

def vaayu_act_one():
    return "As Fili, Kili, Dori, Nori and Ori drive towards the lonely mountain, the extremely loud music coming from their JBL Go 3 speakers attract the a    ttention of some corr     upt goblins. They are stopped      , and are asked for their licence and registration, which none of them had. The goblins instead ask for copper coins or other favours. Not willing to injure their dignity, a fight breaks out. Fili, Kili, Dori, Nori and Ori       are all captured, with the party bus slightly but drivable.   "

def vaayu_act_two():
    return "The bus swerves over the edge of the mountain, drifting across the road and straightening out on           the road. Fili, Kili, Dori, Nori and Ori continue to embrace        each other after the close fall. The bus driver full throttles the bus driver up the incline. The V8 engine        in the bus roars, as the tires               grip onto the gravel road. They reach a hairpin turn, fighting for traction. The driver downshifts hard into the corner. Suddenly, rocks begin falling from above onto the road ahead. The driver hits the brakes, triggering the ABS,          and             counter steering through the sudden wheelspin, hoping to keep the rear axle from snapping."

def vaayu_act_three():
    return "Nori speaks        up, telling Fili, Kili, Dori and Ori about one of his past adventures, from long before he knew them. The rest look confused, as they have known each other almost their entire life. Nori explains how as a child, his parents were killed by an evil man, who tried to kill him as well. But for some unknown reason, Nori lived. All he was left with was a scar on his head,       in the shape of a thunder cloud.          Nori continues to explain his story, explaining how he became a wizard, before letting go of his powers in exchange for his normal life. Fili and Kili are engrossed,          while Dore and Ori have already left. Ori begins telling his story."